// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw2WNASDcJRVHqNHwEMfEsbLfNwJ6E8hQ',
    appId: '1:944051666231:web:f31031ecc79bdcf22baeb2',
    messagingSenderId: '944051666231',
    projectId: 'chatterbox-57a2a',
    authDomain: 'chatterbox-57a2a.firebaseapp.com',
    storageBucket: 'chatterbox-57a2a.firebasestorage.app',
    measurementId: 'G-YWM5PBZW85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2FQKXl5acVLgzBZNYyUusJjqSzsfgUoI',
    appId: '1:944051666231:android:ca844afbb80325ea2baeb2',
    messagingSenderId: '944051666231',
    projectId: 'chatterbox-57a2a',
    storageBucket: 'chatterbox-57a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfhtXR3VEFrHjIWERHJ4DPdJdIYlriOM',
    appId: '1:944051666231:ios:560790fa3cf822022baeb2',
    messagingSenderId: '944051666231',
    projectId: 'chatterbox-57a2a',
    storageBucket: 'chatterbox-57a2a.firebasestorage.app',
    iosBundleId: 'com.example.chatterBoxFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfhtXR3VEFrHjIWERHJ4DPdJdIYlriOM',
    appId: '1:944051666231:ios:560790fa3cf822022baeb2',
    messagingSenderId: '944051666231',
    projectId: 'chatterbox-57a2a',
    storageBucket: 'chatterbox-57a2a.firebasestorage.app',
    iosBundleId: 'com.example.chatterBoxFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw2WNASDcJRVHqNHwEMfEsbLfNwJ6E8hQ',
    appId: '1:944051666231:web:59d3c13c9f3d14812baeb2',
    messagingSenderId: '944051666231',
    projectId: 'chatterbox-57a2a',
    authDomain: 'chatterbox-57a2a.firebaseapp.com',
    storageBucket: 'chatterbox-57a2a.firebasestorage.app',
    measurementId: 'G-V3GGJ41TK0',
  );
}
